security:
  oauth2:
    client:
      okta:
        client-id: zolag5GAKB3z5pd8zT4j
        client-secret: BUhIpGq8P89YmrH10CqcSvfQ8Q2KqHmb0J6rOPQx
        authorization-uri: https://dev-158606.oktapreview.com/oauth2/v1/authorize
        token-uri: https://dev-158606.oktapreview.com/oauth2/v1/token
        user-info-uri: https://dev-158606.oktapreview.com/oauth2/v1/userinfo